version: '3.8'

services:
  webapi:
    build: .
    ports:
      - "9000:80"
    depends_on:
      - mongodb
    environment:
      - MongoDb__Endpoint=mongodb://mongodb:27017
      - MongoDb__CollectionName=News
      - MongoDb__DatabaseName=NewsDb
    volumes:
      - app_data:/app
    restart: always

  mongodb:
    image: mongo:7.0.4-jammy
    container_name: mongodb
    restart: always
    volumes:
      - mongo_data:/data/db

volumes:
  app_data:
  mongo_data:
